// Code generated by protoc-gen-go. DO NOT EDIT.
// source: structs/http_response.proto

/*
Package structs is a generated protocol buffer package.

It is generated from these files:
	structs/http_response.proto
	structs/user_data.proto
	structs/product_data.proto
	structs/serving_data.proto

It has these top-level messages:
	HttpResponse
	UserHttpResponse
	GamePlaytime
	User
	ProductHttpResponse
	ProductPreferences
	ProductsPreferences
	PreferencesMap
	ProductStoreData
	ProductStoreDataDump
	Product
	ProductScoredList
	ProductSortedPreferences
	ServingData
*/
package structs

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type HttpResponse struct {
	ResponseCode uint32 `protobuf:"varint,1,opt,name=response_code,json=responseCode" json:"response_code,omitempty"`
	Timestamp    int64  `protobuf:"varint,2,opt,name=timestamp" json:"timestamp,omitempty"`
	Body         []byte `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
}

func (m *HttpResponse) Reset()                    { *m = HttpResponse{} }
func (m *HttpResponse) String() string            { return proto.CompactTextString(m) }
func (*HttpResponse) ProtoMessage()               {}
func (*HttpResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *HttpResponse) GetResponseCode() uint32 {
	if m != nil {
		return m.ResponseCode
	}
	return 0
}

func (m *HttpResponse) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *HttpResponse) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

func init() {
	proto.RegisterType((*HttpResponse)(nil), "structs.HttpResponse")
}

func init() { proto.RegisterFile("structs/http_response.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 136 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2e, 0x2e, 0x29, 0x2a,
	0x4d, 0x2e, 0x29, 0xd6, 0xcf, 0x28, 0x29, 0x29, 0x88, 0x2f, 0x4a, 0x2d, 0x2e, 0xc8, 0xcf, 0x2b,
	0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x87, 0x4a, 0x2a, 0xa5, 0x72, 0xf1, 0x78,
	0x94, 0x94, 0x14, 0x04, 0x41, 0xa5, 0x85, 0x94, 0xb9, 0x78, 0x61, 0x4a, 0xe3, 0x93, 0xf3, 0x53,
	0x52, 0x25, 0x18, 0x15, 0x18, 0x35, 0x78, 0x83, 0x78, 0x60, 0x82, 0xce, 0xf9, 0x29, 0xa9, 0x42,
	0x32, 0x5c, 0x9c, 0x25, 0x99, 0xb9, 0xa9, 0xc5, 0x25, 0x89, 0xb9, 0x05, 0x12, 0x4c, 0x0a, 0x8c,
	0x1a, 0xcc, 0x41, 0x08, 0x01, 0x21, 0x21, 0x2e, 0x96, 0xa4, 0xfc, 0x94, 0x4a, 0x09, 0x66, 0x05,
	0x46, 0x0d, 0x9e, 0x20, 0x30, 0x3b, 0x89, 0x0d, 0x6c, 0xad, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff,
	0x08, 0x9d, 0x57, 0x4e, 0x95, 0x00, 0x00, 0x00,
}
